### ISSUE TITLE
카드를 컬럼 최상단으로 이동시 제일 아래에 렌더링 되는 문제

### ISSUE THREAD

**Issue by padosum** [woowa-techcamp-2022/web-todo-1#29]
```javascript
export function insertCard(tasks, card, idx) {
  idx = idx || tasks.length;
  return [...tasks.slice(0, idx), card, ...tasks.slice(idx)];
}
```
처음에 했던 로직이 `idx` 파라미터를 넘기지 않기로 명세를 했었는데
해당 로직이 의미없어짐 -> 무조건 넘기고 있음
여기서 문제가 발생
`idx`가 `0`인 경우 `tasks.length`를 가져오게 된다. 그래서 가장 마지막 요소로 추가되는 것 -> 해당 값으로 렌더링됨

**Comment by youngkyo0504** [comment]
오 이해했습니다. idx가 0이면 false니까 그렇군요...
